In [ ]:
import pandas as pd
import numpy as np
import datetime
import json

In [ ]:
file_path = "../content/test.txt"

In [ ]:
column_names = ["Date","Mean_light","min_light","max_light","variance"]

df = pd.read_csv(file_path, names=column_names)
# df.head()

FileNotFoundError: ignored

In [ ]:
df.head()

,Date,Mean_light,min_light,max_light,variance
0,{'date': '29/06/22|13:43:24','mean_light': 151.74,'min_light': 100.25,'max_light': 210.25,'variance': 1080.57}
1,{'date': '29/06/22|13:44:24','mean_light': 154.92,'min_light': 149.27,'max_light': 162.34,'variance': 13.08}
2,{'date': '29/06/22|13:45:24','mean_light': 154.77,'min_light': 145.5,'max_light': 162.84,'variance': 17.57}
3,{'date': '29/06/22|13:46:25','mean_light': 160.75,'min_light': 149.76,'max_light': 163.45,'variance': 11.8}
4,{'date': '29/06/22|13:47:25','mean_light': 161.71,'min_light': 152.51,'max_light': 163.61,'variance': 4.67}

In [ ]:
date_string_format = "%d/%B/%m|%H:%M:%S"

def split_and_take(element_guy):

  return element_guy.split(":")

for ind,row in df.iterrows():
  # case for datetime
  #split
  date_parts = row["Date"].split("':") 
  #take date part that we want
  date = date_parts[1]
  # print(date)
  # print(type(date))
  #turn into datetime object
  date_ = date.replace("|"," ")
  # date_object = datetime.datetime.strptime(date,date_string_format)
  #replace
  row["Date"] = date_

  # case where no '{' or '}'
  # split and take last element in new array 
  row['Mean_light'] = row['Mean_light'].split(":")[1]
  row['min_light'] = row['min_light'].split(":")[1]
  row['max_light'] = row['max_light'].split(":")[1]

  #case for '}'
  #split
  variance_parts = row['variance'].split(":")
  #strip
  variance = variance_parts[1].strip("}")
  #replace
  row["variance"] = variance
  
  # row["Mean_light"] = float(split_and_take(row['Mean_light']))
  # row['min_light'] = float(split_and_take(row['min_light']))
  # row["max_light"] = float(split_and_take(row["max_light"]))
  # row["variance"] = float(split_and_take(row['variance']))

In [ ]:
df.head()

                   Date Mean_light min_light max_light  variance
0   '29/06/22 13:43:24'     151.74    100.25    210.25   1080.57
1   '29/06/22 13:44:24'     154.92    149.27    162.34     13.08
2   '29/06/22 13:45:24'     154.77     145.5    162.84     17.57
3   '29/06/22 13:46:25'     160.75    149.76    163.45      11.8
4   '29/06/22 13:47:25'     161.71    152.51    163.61      4.67

In [ ]:
df["Date"] = pd.to_datetime(df["Date"])

In [ ]:
df.info()

NameError: ignored